# -*- coding: utf-8 -*-
"""Fertility Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfvL3Q_HFRnqMQ0V4z3Nt8qH-KtT46PR
"""

from google.colab import drive
drive.mount('/content/drive')

#filepath to folder where data is housed - specific to each group member
#juliette cd
cd="/content/drive/MyDrive/Drexel Data Science Masters/CS613 - Machine Learning/CS613 final project/"

#valentina cd
cd="/content/drive/MyDrive/CS613 final project/"

#sravya cd
cd= "/content/drive/MyDrive/CS613/Project/"

#jinsu cd
cd = "/content/drive/MyDrive/CS613 final project/"

import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report, roc_curve, auc, precision_score, recall_score, f1_score, confusion_matrix, precision_recall_fscore_support
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

ad = pd.read_csv(cd+"FedCycleData.csv")

ad.head(100)

"""Data cleaning"""

#clean up dataset

#1) set missing values to 'NA'
ad = ad.replace(" ", pd.NA)

#2) drop unusable variables
todrop=['Wedding','Methoddate','Timeattemptpreg','Whychart','Nextpreg','NextpregM','Medvitexplain','MedvitexplainM',
        'MensesScoreDayOne', 'MensesScoreDayTwo','MensesScoreDayThree', 'MensesScoreDayFour', 'MensesScoreDayFive','MensesScoreDaySix',
        'MensesScoreDaySeven', 'MensesScoreDayEight','MensesScoreDayNine', 'MensesScoreDayTen', 'MensesScoreDay11','MensesScoreDay12',
        'MensesScoreDay13', 'MensesScoreDay14','MensesScoreDay15', 'Height', 'Weight','CycleNumber','Group','NumberofDaysofIntercourse',
        'IntercourseInFertileWindow','IntercourseDuringUnusBleed','Spousesame','AgeM', 'LivingkidsM','OccupationM','MaristatusM','ReligionM','EthnicityM',
        'SpousesameM','SchoolyearsM','MedvitsM','Reprocate','Method','Prevmethod','Gynosurgeries', 'Urosurgeries']
ad = ad.drop(todrop, axis=1)
#reasons for dropping:
    #Wedding: date variable unlegible - also not informative for this analysis because no other dates to compare to
    #Methoddate: date variable unlegible - also not informative for this analysis because no other dates to compare to
    #Timeattemptpreg: all are 0 or NA so no variation and therefore not informative
    #Whychart: not defined in codebook
    #Nextpreg: not defined in codebook
    #NextpregM: not defined in codebook
    #Medvitexplain: text response- outside scope of this analysis
    #MedvitexplainM: text response- outside scope of this analysis
    #Menses scores for each day because using total score
    #Height, Weight because using BMI
    #Cyclenumber because not meaningful variable
    #Group because this is just method of cycle tracking
    #Intercourse and Spousesame variables because we are looking at fertile window/ characteristics of mestruation, not reproductive outcomes
    #socidemographics or health data of the male partner - since we are looking at female fertility (except for male income since female income not included)
    #'Reprocate','Method','Prevmethod','Gynosurgeries', 'Urosurgeries' because all highly missing

#3) set variable type for continuous and categorical variables
#continuous
cont=('LengthofCycle', 'MeanCycleLength','EstimatedDayofOvulation', 'LengthofLutealPhase','FirstDayofHigh','TotalNumberofHighDays',
      'TotalHighPostPeak','TotalNumberofPeakDays','TotalDaysofFertility','TotalFertilityFormula', 'LengthofMenses','MeanMensesLength',
      'TotalMensesScore','MeanBleedingIntensity','Age', 'Yearsmarried', 'Numberpreg','Livingkids', 'Miscarriages', 'Abortions',
      'Boys','Girls','BMI')

for c in cont:
  ad[c] = pd.to_numeric(ad[c], errors='coerce')

#categorical
cat=('ClientID', 'CycleWithPeakorNot','ReproductiveCategory','UnusualBleeding','PhasesBleeding',
     'Maristatus', 'Religion', 'Ethnicity', 'Medvits','Breastfeeding')

for c in cat:
  ad[c] = ad[c].astype("category")

  #ordinal
  ord=('IncomeM','Schoolyears')

  for c in ord:
    ad[c] = pd.Categorical(ad[c],ordered=True)


#4) convert boys and girls to # of living children who are boys and girls
ad["Boys"] = np.where(ad["Livingkids"]> 0, ad["Boys"]/ad["Livingkids"], np.nan)
ad["Girls"] = np.where(ad["Livingkids"]> 0, ad["Girls"]/ad["Livingkids"], np.nan)

"""# Exploratory Data Analysis

Missingness
"""

#Examine missingness

#pd.set_option('display.max_rows', None) #run this to display all rows
ad.isnull().sum()

"""Outcome variables"""

#Examine continuous outcome variable (days of fertility)
from matplotlib import colors
from matplotlib.ticker import PercentFormatter

plt.hist(ad['TotalDaysofFertility'], bins=10, edgecolor='black')

#Examine categorical outcome variable (reproductive category)
sns.countplot(x='ReproductiveCategory', data=ad)
plt.show()

#highly unbalanced - must create balanced subdataset

"""Categorical variables"""

## visualizing key menstrual cycle and sociodemographic categorical/ordinal exposure variables

sns.countplot(x='CycleWithPeakorNot', data=ad)
plt.show()

sns.countplot(x='UnusualBleeding', data=ad)
plt.show()

sns.countplot(x='PhasesBleeding', data=ad)
plt.show()

sns.countplot(x='Maristatus', data=ad)
plt.show()

sns.countplot(x='Religion', data=ad)
plt.show()

sns.countplot(x='Ethnicity', data=ad)
plt.show()

sns.countplot(x='Breastfeeding', data=ad)
plt.show()

sns.countplot(x='IncomeM', data=ad)
plt.show()

sns.countplot(x='Schoolyears', data=ad)
plt.show()

sns.countplot(x='Medvits', data=ad)
plt.show()

"""Continuous variables"""

#explore continuous variables
ad.describe()

# Commented out IPython magic to ensure Python compatibility.
## visualizing continuous exposure variables

#histograms: should log-transform any?
# %matplotlib inline
import matplotlib.pyplot as plt
ad.hist(bins=50, figsize=(20,15))
plt.show()

"""Imputation"""

#dealing with missing data

#1) first impute missing values by ClientID

#impute with mean for numerical
numerical_cols = ad.select_dtypes(include=np.number).columns
ad[numerical_cols] = ad[numerical_cols].fillna(ad.groupby('ClientID')[numerical_cols].transform('mean'))

#impute with mode for categorical
cat_cols = ad.select_dtypes(include="category").columns
ad[cat_cols] = ad.groupby("ClientID")[cat_cols].apply(
    lambda g: g.apply(lambda col: col.fillna(col.mode().iloc[0]) if not col.mode().empty else col)
).reset_index(level=0, drop=True)

#2) impute remaining across whole dataset

#impute with mean for numerical
numerical_cols = ad.select_dtypes(include=np.number).columns
ad[numerical_cols] = ad[numerical_cols].fillna(ad[numerical_cols].mean())

#impute with mode for categorical
cat_cols = ad.select_dtypes(include="category").columns
ad[cat_cols] = ad[cat_cols].fillna(ad[cat_cols].mode().iloc[0])

ad.head()

"""Examine relationships between variables and outcome"""

##use T-test to understand relationship bw binary variables and days of fertility

from scipy.stats import ttest_ind

#CycleWithPeakorNot: p value = 1.84e-05 (significant)
group1 = ad[ad['CycleWithPeakorNot']==0]
group2 = ad[ad['CycleWithPeakorNot']==1]
ttest_ind(group1['TotalDaysofFertility'], group2['TotalDaysofFertility'])

#UnusualBleeding: p value = 0.0002 (significant)
group1 = ad[ad['UnusualBleeding']=='0']
group2 = ad[ad['UnusualBleeding']=='1']
ttest_ind(group1['TotalDaysofFertility'], group2['TotalDaysofFertility'])

#Medvits: p value = 0.00852 (significant)
group1 = ad[ad['Medvits']=='0']
group2 = ad[ad['Medvits']=='1']
ttest_ind(group1['TotalDaysofFertility'], group2['TotalDaysofFertility'])

#signficant association between TotalDaysofFertility and CycleWithPeakorNot, UnusualBleeding, Medvits

##use ANOVA to understand relationship bw categorical variables and days of fertility

import scipy.stats as stats

#PhasesBleeding p value = 0.3
stats.f_oneway(ad['TotalDaysofFertility'][ad['PhasesBleeding'] == '0'],
               ad['TotalDaysofFertility'][ad['PhasesBleeding'] == '1'],
               ad['TotalDaysofFertility'][ad['PhasesBleeding'] == '2'],
               ad['TotalDaysofFertility'][ad['PhasesBleeding'] == '3'])

#Maristatus p value = 1.95e-07 (significant)
stats.f_oneway(ad['TotalDaysofFertility'][ad['Maristatus'] == '0'],
               ad['TotalDaysofFertility'][ad['Maristatus'] == '1'],
               ad['TotalDaysofFertility'][ad['Maristatus'] == '2'])

#Religion p value = 0.02 (significant)
stats.f_oneway(ad['TotalDaysofFertility'][ad['Religion'] == '0'],
               ad['TotalDaysofFertility'][ad['Religion'] == '1'],
               ad['TotalDaysofFertility'][ad['Religion'] == '4'])

#Ethnicity p value = 7.62e-10 (significant)
stats.f_oneway(ad['TotalDaysofFertility'][ad['Ethnicity'] == '0'],
               ad['TotalDaysofFertility'][ad['Ethnicity'] == '1'],
               ad['TotalDaysofFertility'][ad['Ethnicity'] == '2'],
               ad['TotalDaysofFertility'][ad['Ethnicity'] == '3'],
               ad['TotalDaysofFertility'][ad['Ethnicity'] == '5'])

#Breastfeeding p value = 0.19
stats.f_oneway(ad['TotalDaysofFertility'][ad['Breastfeeding'] == '0'],
               ad['TotalDaysofFertility'][ad['Breastfeeding'] == '2'],
               ad['TotalDaysofFertility'][ad['Breastfeeding'] == '3'],
               ad['TotalDaysofFertility'][ad['Breastfeeding'] == '4'],
               ad['TotalDaysofFertility'][ad['Breastfeeding'] == '6'])

#IncomeM p value = 7.79e-06 (significant)
stats.f_oneway(ad['TotalDaysofFertility'][ad['IncomeM'] == '0'],
               ad['TotalDaysofFertility'][ad['IncomeM'] == '1'],
               ad['TotalDaysofFertility'][ad['IncomeM'] == '2'],
               ad['TotalDaysofFertility'][ad['IncomeM'] == '3'],
               ad['TotalDaysofFertility'][ad['IncomeM'] == '4'],
               ad['TotalDaysofFertility'][ad['IncomeM'] == '5'])

#Schoolyears p value = 0.016 (significant)
stats.f_oneway(ad['TotalDaysofFertility'][ad['Schoolyears'] == '2'],
               ad['TotalDaysofFertility'][ad['Schoolyears'] == '6'],
               ad['TotalDaysofFertility'][ad['Schoolyears'] == '7'],
               ad['TotalDaysofFertility'][ad['Schoolyears'] == '8'],
               ad['TotalDaysofFertility'][ad['Schoolyears'] == '9'])

#signficant association between TotalDaysofFertility and Maristatus, Religion, Ethnicity, IncomeM, Schoolyears

##use correlation to understand relationship bw cont variables and days of fertility
pd.set_option('display.max_columns', None) #run this to display all rows
corr_matrix = ad.select_dtypes(include=['number']).corr()
corr_matrix

#Total days of fertility is highly correlated with TotalNumberofHighDays (0.78) and moderately correlated with
  #EstimatedDayofOvulation (0.34), FirstDayofHigh (-0.22), TotalNumberofPeakDays (0.23)

#visualize correlation
from pandas.plotting import scatter_matrix

attributes = ad.select_dtypes(include=np.number).columns
#scatter_matrix(ad[attributes], figsize=(12, 12))

scat = scatter_matrix(ad[attributes], alpha=0.2, figsize=(12, 12))
for ax in scat.flatten():
    ax.xaxis.label.set_rotation(90)
    ax.yaxis.label.set_rotation(0)
    ax.yaxis.label.set_ha('right')

plt.tight_layout()
plt.gcf().subplots_adjust(wspace=0, hspace=0)
plt.show()

"""# Data Preprocessing"""

#select features to be included in model - based on t-test, ANOVA, correlations above and apriori knowledge = 14 features

features_out=['ClientID', 'TotalDaysofFertility', 'ReproductiveCategory', 'CycleWithPeakorNot', 'UnusualBleeding', 'Medvits',
              'Maristatus', 'Religion', 'Ethnicity', 'IncomeM', 'Schoolyears', 'TotalNumberofHighDays',
              'EstimatedDayofOvulation', 'FirstDayofHigh', 'TotalNumberofPeakDays','LengthofCycle', 'Age','BMI']
ad2=ad[features_out]
ad2.head()

print("Remaining nulls after imputation:")
print(ad2[features_out].isnull().mean().sort_values(ascending=False).head(50))

#none missing!

#split into training and testing data - splitting on the client level so all repeated observations follow the client

#assign clients to training or testing
clientIDs=ad2["ClientID"].unique()

train_clients, test_clients=train_test_split(clientIDs, test_size=.33, random_state=42)

#now assign observations based on which set client is in
train_set = ad2[ad2["ClientID"].isin(train_clients)]
test_set  = ad2[ad2["ClientID"].isin(test_clients)]

"""Preprocessing for Regression dataset (full dataset)"""

# separate the predictors and the labels

#for regression dataset (full dataset)
x_train = train_set.drop(["TotalDaysofFertility",'ReproductiveCategory',"ClientID"], axis=1) # drop labels and ID
y_train = train_set["TotalDaysofFertility"].copy()
x_test = test_set.drop(["TotalDaysofFertility", 'ReproductiveCategory',"ClientID"], axis=1) # drop labels and ID
y_test = test_set["TotalDaysofFertility"].copy()

#pre-process features
from sklearn.impute import SimpleImputer

#define categorical and continuous
cat_feat = ['CycleWithPeakorNot', 'UnusualBleeding', 'Medvits','Maristatus', 'Religion', 'Ethnicity', 'IncomeM', 'Schoolyears']
num_feat = ['TotalNumberofHighDays', 'EstimatedDayofOvulation', 'FirstDayofHigh', 'TotalNumberofPeakDays','LengthofCycle', 'Age','BMI']

#keep all possible values for caetegorical vairables
cat_categories = {col: ad2[col].astype('category').cat.categories.tolist() for col in cat_feat}

#transform cat using onehotencoder
cat_pipeline = Pipeline(steps=[
    ('onehot', OneHotEncoder(categories=[cat_categories[col] for col in cat_feat],handle_unknown='ignore',drop='first'))
])

#transform cont using z-score
num_pipeline = Pipeline([
        ('std_scaler', StandardScaler()),
    ])

#full pipeline
full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_feat),
        ("cat", cat_pipeline, cat_feat),
    ])

#fit on x_train
x_train2 = full_pipeline.fit_transform(x_train)

#transform on x_test (using x_train means/stds)
x_test2 = full_pipeline.transform(x_test)

#prep for assessing feature importance for models

#extract feature names from ColumnTransformer
num_feat_out = full_pipeline.named_transformers_['num']['std_scaler'].get_feature_names_out(num_feat)

cat_feat_out = full_pipeline.named_transformers_['cat']['onehot'].get_feature_names_out(cat_feat)

all_feat = list(num_feat_out) + list(cat_feat_out)


#map transformed features onto original features (to deal with one-hot-expanded columns)
groups = {}
for feat in num_feat:
    groups[feat] = [feat]  # numeric unchanged

for feat in cat_feat:
    groups[feat] = [col for col in all_feat if col.startswith(feat)]

"""Preprocessing for Classification dataset (subset)"""

# Balance the dataset
train_set["ReproductiveCategory"] = pd.to_numeric(train_set["ReproductiveCategory"], errors="coerce")
df = train_set[train_set["ReproductiveCategory"].isin([0, 1])].copy()
df_pos = df[df["ReproductiveCategory"] == 1]
df_neg = df[df["ReproductiveCategory"] == 0]

n_pos = len(df_pos)
df_neg_sampled = df_neg.sample(n=n_pos, random_state=0)

df_bal = pd.concat([df_pos, df_neg_sampled]).sample(frac=1, random_state=0).reset_index(drop=True)

print("\nBalanced class counts:")
print(df_bal["ReproductiveCategory"].value_counts())
print("Balanced shape:", df_bal[features_out].shape)

# separate the predictors and the labels

#for regression dataset (full dataset)
x_train_class = df_bal.drop(["TotalDaysofFertility",'ReproductiveCategory',"ClientID"], axis=1) # drop labels and ID
y_train_class = df_bal["ReproductiveCategory"].copy()

#x_test is same as that used in regression
y_test_class = test_set["ReproductiveCategory"].copy()

#pre-process features

#fit on x_train
x_train_class2 = full_pipeline.fit_transform(x_train_class)

"""# Regression Models

###Linear Regression
"""

#Create a Linear Regression model object
linreg = LinearRegression()
linreg.fit(x_train2, y_train)
pred_lin = linreg.predict(x_test2)

#Calculate Mean Squared Error (MSE): average squared difference between actual and predicted values
mse_lr = mean_squared_error(y_test, pred_lin)
r2_lr = r2_score(y_test, pred_lin) #Calculate R-squared (R²): proportion of variance in the fertile-window length explained by the model

print("Linear Regression MSE:", mse_lr)
print("Linear Regression R2:", r2_lr )

"""### Random Forest"""

#Tunning with the paramaters
param_grid = {
    'n_estimators': [100, 300, 500], #this tuning pick the best number of dataset
    'max_depth': [None, 10, 20], #decides which is best
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

rf = RandomForestRegressor(random_state=0)

#Grid search will run the RF with every combination of these settings
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, scoring='neg_mean_squared_error', cv=5, n_jobs=-1)

#fit the tunning on training set
grid_search.fit(x_train2, y_train)
# Best model found
best_rf = grid_search.best_estimator_

print("Best Random Forest parameters:", grid_search.best_params_)

pred_rf_tuned = best_rf.predict(x_test2)

mse_tuned = mean_squared_error(y_test, pred_rf_tuned)
r2_tuned = r2_score(y_test, pred_rf_tuned)

print("Random Forest MSE:", mse_tuned)
print("Random Forest R2:", r2_tuned)

"""### Regression Ensemble"""

#used 0.5 to give them equal weights
pred_ensemble_reg = 0.5 * pred_lin + 0.5 * pred_rf_tuned

mse_ensemble = mean_squared_error(y_test, pred_ensemble_reg)
r2_ensemble = r2_score(y_test, pred_ensemble_reg)

print("Ensemble MSE:", mse_ensemble)
print("Ensemble R2:", r2_ensemble)

# Interpretation
rmse_lr = np.sqrt(mse_lr)
rmse_rf = np.sqrt(mse_tuned)
rmse_ensemble = np.sqrt(mse_ensemble)

print("\nINTERPRETATION OF RESULTS")
print(f"Linear Regression predicts fertile-window length with an RMSE of ~ {rmse_lr:.2f} days and explains {r2_lr*100:.1f}% of the variance.")
print(f"Random Forest achieved a similar prediction error (RMSE ~ {rmse_rf:.2f} days) and explains {r2_tuned*100:.1f}% of variance, indicating that it captures some nonlinear structure that the linear model cannot fully represent")
print(f"The ensemble model, which averages predictions from both models, improved performance further (RMSE ~ {rmse_ensemble:.2f} days) and explains {r2_ensemble*100:.1f}% of variance.This suggests that the two models capture complementary aspects of the data.")
print(f"The underlying relationship appears mostly linear, although the improvement from the ensemble indicates that some nonlinear patterns or interactions are also present.")

#Feature importance

#aggregate importance scores
fimportance_df = pd.DataFrame({
    "feature": all_feat,
    "importance": best_rf.feature_importances_
})

agg_importance = {
    orig: fimportance_df.loc[fimportance_df["feature"].isin(cols), "importance"].sum()
    for orig, cols in groups.items()
}

agg_importance = (pd.DataFrame.from_dict(agg_importance, orient='index', columns=['importance'])).sort_values('importance', ascending=False)


plt.figure(figsize=(8,6))
sns.barplot(x=agg_importance['importance'], y=agg_importance.index)
plt.title("Random Forest Regression Feature Importance")
plt.tight_layout()
plt.show()

"""# Classification Models

Logistic Regression
"""

#Basic model
logreg = LogisticRegression(class_weight="balanced", max_iter=500, random_state=42)

#Hyperparameter tuning
from sklearn.model_selection import GridSearchCV

param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet'],
    'C': [0.01, 0.1, 1, 10],
    'solver': ['saga'],
    'l1_ratio': [0.0, 0.5, 1.0],
}

grid_search = GridSearchCV(logreg, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(x_train_class2, y_train_class)

print("Best parameters:", grid_search.best_params_)
print("Best CV score:", grid_search.best_score_)

#result
#Best parameters: {'C': 10, 'l1_ratio': 0.0, 'penalty': 'l2', 'solver': 'saga'}
#Best CV score: 0.9241666666666667

#Update model with hyperparameters
logreg2 = LogisticRegression(class_weight="balanced", max_iter=500, random_state=42, C=10, solver='saga', penalty='l2')

# Logistic Regression Model
logreg2.fit(x_train_class2, y_train_class)
pred_log = logreg2.predict(x_test2)

# Evaluate
print("=== Logistic Regression Results ===")

print("Accuracy: ", round(accuracy_score(y_test_class, pred_log), 4))
print("Precision:", round(precision_score(y_test_class, pred_log), 4))
print("Recall:   ", round(recall_score(y_test_class, pred_log), 4))
print("F1 Score: ", round(f1_score(y_test_class, pred_log), 4))

cm = confusion_matrix(y_test_class, pred_log)
print("\nConfusion Matrix (rows=true, cols=pred):\n", cm)

#Feature importance

#get coefficients
coefs = np.abs(logreg2.coef_[0])

#aggregate importance scores (bc transformed features in model)
fimportance_df = pd.DataFrame({
    "feature": all_feat,
    "importance": coefs
})

agg_importance = {
       orig: fimportance_df.loc[fimportance_df["feature"].isin(cols), "importance"].mean() #use mean here so don't inflate importance of var with many categories
    for orig, cols in groups.items()
}

agg_importance = (pd.DataFrame.from_dict(agg_importance, orient='index', columns=['importance'])).sort_values('importance', ascending=False)


plt.figure(figsize=(8,6))
sns.barplot(x=agg_importance['importance'], y=agg_importance.index)
plt.title("Logistic Regression Feature Importance\n (based on coefficients)")
plt.tight_layout()
plt.show()

"""Gaussian Naive Bayes"""

#GNB only uses numeric features so re-do preprocessing just to include z-score of cont variables
x_train_class_gnb=x_train_class.drop(cat_feat, axis=1)
x_test_class_gnb=x_test.drop(cat_feat, axis=1)

#gnb pipeline
gnb_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_feat)
    ])

#fit on x_train_class
x_train_class_gnb2 = gnb_pipeline.fit_transform(x_train_class_gnb)

#transform on x_test (using x_train_class means/stds)
x_test_class_gnb2 = gnb_pipeline.transform(x_test_class_gnb)

#use normal y_train_class and y_test_class

# Train model (only uses numeric features)
gnb = GaussianNB(var_smoothing = 1e-09)
gnb.fit(x_train_class_gnb2, y_train_class)
pred_gnb= gnb.predict(x_test_class_gnb2)

# Evaluation
acc = accuracy_score(y_test_class, pred_gnb)
prec, rec, f1, _ = precision_recall_fscore_support(
    y_test_class, pred_gnb, average="binary", pos_label=1
)

cm = confusion_matrix(y_test_class, pred_gnb)

print("\n=== Gaussian Naive Bayes Results ===")
print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1 Score:  {f1:.4f}")

print("\nConfusion Matrix (rows=true, cols=pred):")
print(cm)

#feature importance

means =gnb.theta_
variances = gnb.var_

#normalized mean diff importance
importance = np.abs(means[1] - means[0]) / np.sqrt(variances[0] + variances[1])

feat_imp = pd.DataFrame({
    "feature": num_feat,
    "importance": importance
}).sort_values(by="importance", ascending=False)


plt.figure(figsize=(6, 4))
plt.barh(feat_imp["feature"].iloc[:25][::-1],
         feat_imp["importance"].iloc[:25][::-1])
plt.xlabel("Gaussian NB Feature Importance (Norm. Mean Difference)")
plt.title("Feature Importance - Gaussian Naive Bayes")
plt.tight_layout()
plt.show()